version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      go-modules:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/infra"
    schedule:
      interval: "weekly"
    groups:
      infra-npm:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    groups:
      web-npm:
        patterns:
          - "*"
