// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package ssr

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Thailand Gift Shop</title><link rel=\"icon\" href=\"/static/favicon.ico\" sizes=\"any\"><link rel=\"icon\" href=\"/static/favicon.svg\" type=\"image/svg+xml\"><link rel=\"apple-touch-icon\" href=\"/static/apple-touch-icon.png\" sizes=\"180x180\"><link rel=\"manifest\" href=\"/static/site.webmanifest\"><link rel=\"stylesheet\" href=\"/static/assets/app.css\"><script src=\"/static/vendor/htmx.min.js\" defer></script></head><body class=\"min-h-screen bg-amber-50 text-stone-950\"><main class=\"flex min-h-screen items-center justify-center px-6 py-12\"><section class=\"w-full max-w-xl rounded-3xl border border-amber-200 bg-white p-8 shadow-2xl shadow-amber-900/10\"><p class=\"mb-3 text-sm font-semibold uppercase tracking-widest text-amber-700\">Thailand Gift Shop</p><h1 class=\"text-4xl font-bold tracking-tight text-stone-950\">Hello, world!</h1><p id=\"hello-status\" class=\"mt-5 rounded-2xl bg-amber-100 px-5 py-4 text-lg font-medium text-stone-900\">Hello from thailandgiftshop.com</p><a class=\"mt-6 inline-flex items-center justify-center rounded-full bg-stone-950 px-6 py-3 text-sm font-bold uppercase tracking-widest text-amber-50 shadow-lg shadow-stone-950/20 transition hover:-translate-y-0.5 hover:bg-amber-700 focus:outline-none focus:ring-4 focus:ring-amber-300\" href=\"/?hello=fallback\" hx-get=\"/hello-fragment\" hx-target=\"#hello-status\" hx-swap=\"innerHTML\">Refresh greeting with HTMX</a></section></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
